name: SLSA Go Releaser

on:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  build:
    permissions:
      id-token: write # For Sigstore signing
      contents: write # Needed to upload binary & provenance assets to the release
      actions: read  # Needed to inspect workflow execution details
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v2.0.0
    with:
      config-file: .slsa-goreleaser.yml
