name: SLSA Go Releaser

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write # Needed for cryptographic signing via Sigstore
  contents: write # Needed to create the release and upload assets
  actions: read  # Needed to inspect workflow execution details

jobs:
  build:
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v2.0.0
    with:
      config-file: .slsa-goreleaser.yml
